### ISSUE TITLE
Revisions tab isn't displaying

### ISSUE THREAD

**Issue by Humni** [EdisonLV/oc-revisions-plugin#2]
Not exactly sure why this is happening but the revisions tab isn't displaying on a fresh install. I tried creating a new page in the CMS but it also wasn't working. 

Is this plugin working on other sites as I haven't had any luck so far

![image](https://user-images.githubusercontent.com/5545538/82768386-ce29bb80-9e82-11ea-8b9a-1606fb254a33.png)

**Comment by EdOzolins** [comment]
Do you have theme logs enabled?
